import type { SimpleSkillSpec } from '../utils/simpleSkillTree';

type SkillDefinition = {
  id: string;
  name_ko: string;
  domain: string;
  level: number;
  description_ko: string;
  prereq: string[];
};

type BossSkillGroup = {
  boss_id: string;
  name_ko: string;
  description_ko: string;
  skills: SkillDefinition[];
};

const BOSS_SKILL_GROUPS: BossSkillGroup[] = [
  {
    boss_id: 'TS_LIMIT_SEQ',
    name_ko: '수열의 극한·급수',
    description_ko:
      '등차·등비수열과 수열 표기법을 바탕으로 수열의 극한 개념(수렴·발산·단조·유계)을 이해하고, 부분합과 급수, 특히 등비급수의 합과 수렴 조건까지 다루는 최종 단원.',
    skills: [
      {
        id: 'NUM_INT_FRAC',
        name_ko: '정수·유리수의 사칙연산',
        domain: '수와 연산',
        level: 1,
        description_ko: '정수, 분수, 소수의 사칙연산과 계산 순서를 이해한다.',
        prereq: [],
      },
      {
        id: 'ALG_EXPR_BASIC',
        name_ko: '문자와 식 기초',
        domain: '대수',
        level: 2,
        description_ko: '상황을 문자와 식으로 나타내고, 간단한 식의 값을 구할 수 있다.',
        prereq: ['NUM_INT_FRAC'],
      },
      {
        id: 'SEQ_NOTATION_BASIC',
        name_ko: '수열 표기와 일반항 기초',
        domain: '수열',
        level: 3,
        description_ko: '수열 {a_n}의 표기법과 n번째 항 a_n의 의미를 이해하고, 간단한 규칙에서 일반항을 찾을 수 있다.',
        prereq: ['ALG_EXPR_BASIC'],
      },
      {
        id: 'SEQ_ARITH',
        name_ko: '등차수열의 일반항',
        domain: '수열',
        level: 3,
        description_ko: '공차 d, 첫째항 a_1 개념을 알고, 등차수열의 n번째 항 a_n = a_1 + (n-1)d를 구할 수 있다.',
        prereq: ['SEQ_NOTATION_BASIC', 'NUM_INT_FRAC'],
      },
      {
        id: 'SEQ_GEOM',
        name_ko: '등비수열의 일반항',
        domain: '수열',
        level: 3,
        description_ko: '등비수열의 공비 r, 첫째항 a_1을 이해하고, a_n = a_1 r^{n-1} 를 구할 수 있다.',
        prereq: ['SEQ_NOTATION_BASIC', 'NUM_INT_FRAC'],
      },
      {
        id: 'SEQ_RECUR',
        name_ko: '점화식으로 정의된 수열',
        domain: '수열',
        level: 4,
        description_ko: 'a_{n+1} = a_n + d, a_{n+1} = r a_n 같은 점화식으로 정의된 수열을 이해하고, 몇 개 항을 구할 수 있다.',
        prereq: ['SEQ_NOTATION_BASIC', 'SEQ_ARITH', 'SEQ_GEOM'],
      },
      {
        id: 'SEQ_SUM_ARITH',
        name_ko: '등차수열의 합',
        domain: '수열',
        level: 4,
        description_ko: '등차수열의 앞에서 n개 항의 합 S_n 공식을 이해하고, 다양한 문제에 적용할 수 있다.',
        prereq: ['SEQ_ARITH', 'NUM_INT_FRAC'],
      },
      {
        id: 'SEQ_SUM_GEOM_FINITE',
        name_ko: '등비수열의 유한합',
        domain: '수열',
        level: 4,
        description_ko: '등비수열의 앞에서 n개 항의 합 S_n 공식을 이해하고, r ≠ 1 인 경우 합을 계산할 수 있다.',
        prereq: ['SEQ_GEOM', 'NUM_INT_FRAC'],
      },
      {
        id: 'CALC_SIGMA',
        name_ko: '시그마(Σ) 기호와 유한합',
        domain: '해석',
        level: 5,
        description_ko: '일정한 규칙을 가진 합을 시그마(Σ) 기호로 나타내고, 등차·등비수열의 합을 Σ 기호로 표현하여 계산할 수 있다.',
        prereq: ['SEQ_SUM_ARITH', 'SEQ_SUM_GEOM_FINITE', 'ALG_EXPR_BASIC'],
      },
      {
        id: 'SEQ_LIMIT_INTRO',
        name_ko: '수열의 극한 개념(수렴·발산)',
        domain: '해석',
        level: 5,
        description_ko: 'a_n → L 의 의미를 말로 설명하고, 1/n, r^n (|r|<1), n 같은 기본 예에서 수렴·발산을 구분할 수 있다.',
        prereq: ['SEQ_NOTATION_BASIC', 'NUM_INT_FRAC'],
      },
      {
        id: 'SEQ_LIMIT_TECH_BASIC',
        name_ko: '기본 수열의 극한 계산',
        domain: '해석',
        level: 6,
        description_ko: '다항식 꼴, 분수꼴, 등비수열 꼴의 수열에 대해 극한값을 계산할 수 있다.',
        prereq: ['SEQ_LIMIT_INTRO', 'ALG_EXPR_BASIC', 'ALG_POLY_BASIC'],
      },
      {
        id: 'SEQ_MONO_BOUND',
        name_ko: '단조수열·유계수열과 수렴',
        domain: '해석',
        level: 6,
        description_ko: '수열의 단조성(단조증가·단조감소)과 유계성 개념을 이해하고, 단조·유계이면 수렴한다는 사실을 직관적으로 설명할 수 있다.',
        prereq: ['SEQ_LIMIT_INTRO', 'SEQ_ARITH', 'SEQ_GEOM'],
      },
      {
        id: 'SERIES_PARTIAL_SUM',
        name_ko: '부분합과 급수',
        domain: '해석',
        level: 7,
        description_ko: '급수 ∑ a_n 의 부분합 수열 S_n = ∑_{k=1}^n a_k 개념을 이해하고, S_n과 a_n 사이의 관계를 설명할 수 있다.',
        prereq: ['SEQ_NOTATION_BASIC', 'CALC_SIGMA'],
      },
      {
        id: 'SERIES_GEOM_INFINITE',
        name_ko: '무한등비급수와 수렴 조건',
        domain: '해석',
        level: 7,
        description_ko: '무한등비급수 ∑ a_1 r^{n-1} 가 |r|<1 일 때 수렴하고, 그 합이 a_1/(1-r) 이 됨을 이해한다.',
        prereq: ['SEQ_GEOM', 'SEQ_SUM_GEOM_FINITE', 'SERIES_PARTIAL_SUM', 'SEQ_LIMIT_INTRO'],
      },
      {
        id: 'SERIES_APPL_SIMPLE',
        name_ko: '무한등비급수 응용(금융·확률·기하)',
        domain: '해석',
        level: 8,
        description_ko: '무한등비급수를 이용해 저축·대출 상환, 확률 모형, 기하적 패턴(프랙탈 등)에서 합을 계산하는 문제를 해결한다.',
        prereq: ['SERIES_GEOM_INFINITE', 'NUM_INT_FRAC'],
      },
      {
        id: 'TS_LIMIT_SEQ',
        name_ko: '보스: 수열의 극한·급수',
        domain: '보스',
        level: 9,
        description_ko:
          '수열의 극한과 단조·유계 개념, 등차·등비수열의 일반항·합, 무한등비급수의 수렴과 합 공식을 자유롭게 설명하고 다양한 상황 문제를 스스로 모델링·해결할 수 있는 상태.',
        prereq: [
          'SEQ_ARITH',
          'SEQ_GEOM',
          'SEQ_RECUR',
          'SEQ_LIMIT_TECH_BASIC',
          'SEQ_MONO_BOUND',
          'SERIES_PARTIAL_SUM',
          'SERIES_GEOM_INFINITE',
          'SERIES_APPL_SIMPLE',
        ],
      },
    ],
  },
  {
    boss_id: 'TS_EXP_LOG',
    name_ko: '지수·로그함수',
    description_ko:
      '지수법칙과 로그의 정의·성질, 역함수 개념을 바탕으로 지수함수·로그함수의 그래프와 성질을 이해하고, 지수·로그방정식과 실생활 성장·감소 모델을 다루는 최종 단원.',
    skills: [
      {
        id: 'NUM_INT_FRAC',
        name_ko: '정수·유리수의 사칙연산',
        domain: '수와 연산',
        level: 1,
        description_ko: '정수, 분수, 소수의 사칙연산과 지수표기(10^n 등)를 정확히 계산할 수 있다.',
        prereq: [],
      },
      {
        id: 'NUM_REAL_ROOT',
        name_ko: '실수와 제곱근',
        domain: '수와 연산',
        level: 2,
        description_ko: '제곱근, 무리수의 개념을 이해하고, 근호를 포함한 수의 대소 관계와 기본 계산을 할 수 있다.',
        prereq: ['NUM_INT_FRAC'],
      },
      {
        id: 'EXP_INT_LAWS',
        name_ko: '정수 지수와 지수법칙',
        domain: '대수',
        level: 3,
        description_ko: 'a^m·a^n, (a^m)^n, (ab)^n, a^{-n} 등 정수 지수에 대한 지수법칙을 이해하고, 지수식을 간단히 할 수 있다.',
        prereq: ['NUM_INT_FRAC'],
      },
      {
        id: 'EXP_RATIONAL',
        name_ko: '유리수 지수와 거듭제곱·근',
        domain: '대수',
        level: 3,
        description_ko: 'a^{1/n}, a^{m/n} 의 의미를 이해하고, 거듭제곱과 근의 관계를 이용해 식을 변형할 수 있다.',
        prereq: ['EXP_INT_LAWS', 'NUM_REAL_ROOT'],
      },
      {
        id: 'ALG_EXPR_BASIC',
        name_ko: '문자와 식 기초',
        domain: '대수',
        level: 3,
        description_ko: '문자로 식을 표현하고, 대입을 통해 식의 값을 구할 수 있다.',
        prereq: ['NUM_INT_FRAC'],
      },
      {
        id: 'FUNC_BASIC',
        name_ko: '함수 개념 기초',
        domain: '함수',
        level: 4,
        description_ko: '함수, 정의역·치역, 그래프를 이용해 ‘입력→출력’ 관계를 표현하고 해석할 수 있다.',
        prereq: ['ALG_EXPR_BASIC'],
      },
      {
        id: 'FUNC_INVERSE',
        name_ko: '역함수 개념',
        domain: '함수',
        level: 4,
        description_ko: '일대일함수의 역함수 개념을 이해하고, y=x 에 대한 대칭으로 그래프를 해석한다.',
        prereq: ['FUNC_BASIC'],
      },
      {
        id: 'FUNC_EXP',
        name_ko: '지수함수의 그래프와 성질',
        domain: '함수',
        level: 5,
        description_ko:
          'a>0, a≠1 인 지수함수 y = a^x 의 정의역·치역, 그래프 모양(증가/감소)과 x→±∞에서의 거동을 이해한다.',
        prereq: ['EXP_RATIONAL', 'FUNC_BASIC'],
      },
      {
        id: 'LOG_DEF',
        name_ko: '로그의 정의',
        domain: '대수',
        level: 5,
        description_ko: 'a>0, a≠1 일 때, a^x = b ⇔ log_a b = x 의 관계로 로그의 뜻을 이해하고, 간단한 로그값을 구할 수 있다.',
        prereq: ['EXP_INT_LAWS', 'NUM_INT_FRAC'],
      },
      {
        id: 'LOG_LAWS',
        name_ko: '로그의 성질(곱, 몫, 거듭제곱)',
        domain: '대수',
        level: 6,
        description_ko: 'log_a(xy), log_a(x/y), log_a(x^r) 등 로그법칙을 이해하고, 로그식을 간단히 하거나 변형할 수 있다.',
        prereq: ['LOG_DEF', 'ALG_EXPR_BASIC'],
      },
      {
        id: 'FUNC_LOG',
        name_ko: '로그함수의 그래프와 성질',
        domain: '함수',
        level: 6,
        description_ko: '로그함수 y = log_a x 의 정의역(0,∞), 치역(모든 실수), 그래프 모양과 a>1, 0<a<1 인 경우의 차이를 이해한다.',
        prereq: ['LOG_LAWS', 'FUNC_INVERSE', 'FUNC_EXP'],
      },
      {
        id: 'EXP_LOG_INVERSE',
        name_ko: '지수함수와 로그함수의 역함수 관계',
        domain: '함수',
        level: 6,
        description_ko: 'y = a^x 와 y = log_a x 가 서로 역함수 관계이며, 두 그래프가 y=x 에 대해 대칭임을 설명할 수 있다.',
        prereq: ['FUNC_INVERSE', 'FUNC_EXP', 'FUNC_LOG'],
      },
      {
        id: 'EXP_LOG_GRAPH_COMPARE',
        name_ko: '밑에 따른 그래프 비교',
        domain: '함수',
        level: 7,
        description_ko: '서로 다른 밑 a, b 에 대해 지수·로그함수의 그래프를 비교하고, 성장 속도와 증가/감소 성질을 설명한다.',
        prereq: ['FUNC_EXP', 'FUNC_LOG'],
      },
      {
        id: 'EXP_LOG_EQUATIONS',
        name_ko: '지수·로그방정식 풀이',
        domain: '대수',
        level: 7,
        description_ko: '밑을 같게 맞추거나 로그법칙을 이용해 간단한 지수방정식과 로그방정식을 풀 수 있다.',
        prereq: ['EXP_INT_LAWS', 'LOG_LAWS', 'ALG_EXPR_BASIC'],
      },
      {
        id: 'EXP_GROWTH_DECAY',
        name_ko: '지수함수의 성장·감소 모델',
        domain: '모델링',
        level: 7,
        description_ko: '인구 성장, 방사능 붕괴, 복리 이자 등 지수함수로 표현되는 실생활 상황을 모델링하고, 간단한 예측 계산을 할 수 있다.',
        prereq: ['FUNC_EXP', 'NUM_INT_FRAC'],
      },
      {
        id: 'LOG_SCALE_APPL',
        name_ko: '로그 스케일과 단위(데시벨·지진 규모 등)',
        domain: '모델링',
        level: 8,
        description_ko: '데시벨, 리히터 규모 등 로그 스케일의 의미를 이해하고, 값의 차이가 실제 크기의 몇 배 차이인지 설명할 수 있다.',
        prereq: ['FUNC_LOG', 'LOG_LAWS'],
      },
      {
        id: 'TS_EXP_LOG',
        name_ko: '보스: 지수·로그함수',
        domain: '보스',
        level: 9,
        description_ko:
          '지수법칙과 로그의 정의·성질, 지수함수·로그함수의 그래프와 역함수 관계를 자유롭게 설명하고, 지수·로그방정식과 성장·감소 모델링 문제를 스스로 설계·해결할 수 있는 상태.',
        prereq: [
          'EXP_RATIONAL',
          'FUNC_EXP',
          'LOG_LAWS',
          'FUNC_LOG',
          'EXP_LOG_INVERSE',
          'EXP_LOG_EQUATIONS',
          'EXP_GROWTH_DECAY',
          'LOG_SCALE_APPL',
        ],
      },
    ],
  },
  {
    boss_id: 'TS_TRIG',
    name_ko: '삼각함수·삼각법',
    description_ko:
      '각·삼각형·닮음을 바탕으로 삼각비, 단위원 삼각함수, 그래프와 기본 성질, 사인·코사인 법칙을 이용해 임의의 삼각형을 해결하는 보스 스킬.',
    skills: [
      {
        id: 'ANGLE_DEG_BASIC',
        name_ko: '각도와 도 단위(°) 기초',
        domain: '도형과 측정',
        level: 1,
        description_ko: '각의 크기를 도(°)로 나타내고, 각도기를 사용해 각을 재고 그릴 수 있다.',
        prereq: [],
      },
      {
        id: 'TRI_RIGHT_SIMILAR',
        name_ko: '직각삼각형 닮음과 비',
        domain: '도형과 측정',
        level: 2,
        description_ko: '직각삼각형의 닮음 조건을 이해하고, 대응변의 비를 이용해 길이를 구할 수 있다.',
        prereq: ['ANGLE_DEG_BASIC'],
      },
      {
        id: 'GEO_PYTHAGORAS',
        name_ko: '피타고라스 정리',
        domain: '도형과 측정',
        level: 2,
        description_ko: '직각삼각형에서 빗변과 다른 두 변 사이의 관계 a² + b² = c² 를 이해하고 활용할 수 있다.',
        prereq: ['TRI_RIGHT_SIMILAR'],
      },
      {
        id: 'TRIG_RATIO_RIGHT',
        name_ko: '직각삼각형에서의 삼각비(sin, cos, tan)',
        domain: '삼각함수',
        level: 3,
        description_ko: '직각삼각형에서 예각의 사인, 코사인, 탄젠트를 변의 길이의 비로 정의하고 계산할 수 있다.',
        prereq: ['TRI_RIGHT_SIMILAR', 'GEO_PYTHAGORAS'],
      },
      {
        id: 'TRIG_TABLE_SPECIAL',
        name_ko: '특수각(30°, 45°, 60°)의 삼각비',
        domain: '삼각함수',
        level: 3,
        description_ko: '정삼각형, 정사각형을 이용해 30°, 45°, 60°의 삼각비 값을 유도하고 기억·활용할 수 있다.',
        prereq: ['TRIG_RATIO_RIGHT'],
      },
      {
        id: 'TRIG_APP_HEIGHT_DISTANCE',
        name_ko: '삼각비를 이용한 높이·거리 구하기',
        domain: '삼각법 응용',
        level: 4,
        description_ko: '실제 상황에서 시각·거리·각도 정보를 사용하여 높이나 거리를 삼각비로 모델링하고 계산할 수 있다.',
        prereq: ['TRIG_RATIO_RIGHT', 'TRIG_TABLE_SPECIAL'],
      },
      {
        id: 'COORD_PLANE',
        name_ko: '좌표평면과 점의 좌표',
        domain: '도형과 측정',
        level: 3,
        description_ko: '좌표평면에서 점을 (x, y)로 나타내고, 사분면과 좌표의 의미를 이해한다.',
        prereq: [],
      },
      {
        id: 'ANGLE_RAD',
        name_ko: '라디안(radian)과 호의 길이',
        domain: '도형과 측정',
        level: 4,
        description_ko: '각의 크기를 라디안으로 나타내는 방법을 이해하고, 원의 호의 길이·부채꼴 넓이와 연결할 수 있다.',
        prereq: ['ANGLE_DEG_BASIC'],
      },
      {
        id: 'TRIG_UNIT_CIRCLE',
        name_ko: '단위원에서의 삼각함수 정의',
        domain: '삼각함수',
        level: 5,
        description_ko: '반지름 1인 원 위의 점 좌표를 이용해 임의의 실수 각도의 sin, cos, tan을 정의하고, 사분면에 따른 부호를 이해한다.',
        prereq: ['COORD_PLANE', 'ANGLE_RAD', 'TRIG_RATIO_RIGHT'],
      },
      {
        id: 'TRIG_SIGN_QUADRANT',
        name_ko: '각도 범위와 사분면별 삼각함수 부호',
        domain: '삼각함수',
        level: 5,
        description_ko: '0~360°(또는 0~2π) 범위에서 각에 따른 삼각함수의 부호와 기준각(참조각)을 이용한 값 계산을 할 수 있다.',
        prereq: ['TRIG_UNIT_CIRCLE'],
      },
      {
        id: 'TRIG_GRAPH_BASIC',
        name_ko: 'y = sin x, cos x, tan x 그래프',
        domain: '함수',
        level: 6,
        description_ko: '삼각함수를 함수로 보고, y = sin x, cos x, tan x의 그래프와 주기·진폭·평균값의 의미를 이해한다.',
        prereq: ['TRIG_UNIT_CIRCLE', 'COORD_PLANE'],
      },
      {
        id: 'TRIG_IDENT_BASIC',
        name_ko: '기본 삼각함수 관계(sin²x + cos²x = 1 등)',
        domain: '삼각함수',
        level: 6,
        description_ko: 'tan x = sin x / cos x, sin²x + cos²x = 1 같은 기본 삼각함수 관계를 이해하고, 간단한 식을 변형할 수 있다.',
        prereq: ['TRIG_UNIT_CIRCLE'],
      },
      {
        id: 'TRIG_ADD_FORMULAE',
        name_ko: '삼각함수 덧셈정리( sin(a±b), cos(a±b) )',
        domain: '삼각함수',
        level: 7,
        description_ko: '삼각함수 덧셈정리를 이해하고, 간단한 값 계산과 삼각함수 식의 변형에 활용할 수 있다.',
        prereq: ['TRIG_IDENT_BASIC'],
      },
      {
        id: 'TRI_SINE_LAW',
        name_ko: '사인 법칙',
        domain: '삼각법',
        level: 6,
        description_ko: 'sin 법칙을 이용해 삼각형의 변과 각 사이의 관계를 이해하고, 일부 변·각이 주어졌을 때 나머지를 구할 수 있다.',
        prereq: ['TRIG_RATIO_RIGHT', 'ANGLE_DEG_BASIC'],
      },
      {
        id: 'TRI_COSINE_LAW',
        name_ko: '코사인 법칙',
        domain: '삼각법',
        level: 7,
        description_ko:
          '코사인 법칙을 통해 삼각형 세 변 또는 두 변과 끼인각이 주어졌을 때 나머지 요소를 구하고, 삼각형의 유형(예각/직각/둔각)을 판별할 수 있다.',
        prereq: ['GEO_PYTHAGORAS', 'TRI_SINE_LAW'],
      },
      {
        id: 'TRI_SOLVE_GENERAL',
        name_ko: '임의 삼각형 풀이와 넓이',
        domain: '삼각법 응용',
        level: 8,
        description_ko: '사인·코사인 법칙과 삼각함수 넓이 공식(S = 1/2 ab sin C 등)을 이용하여 임의 삼각형의 변·각·넓이를 구하는 문제를 해결한다.',
        prereq: ['TRI_SINE_LAW', 'TRI_COSINE_LAW', 'TRIG_TABLE_SPECIAL'],
      },
      {
        id: 'TS_TRIG',
        name_ko: '보스: 삼각함수·삼각법 마스터',
        domain: '보스',
        level: 9,
        description_ko:
          '직각삼각형 삼각비부터 단위원 삼각함수·그래프·기본 항등식, 사인·코사인 법칙까지 연결하여 임의 삼각형 문제와 함수 문제를 자유롭게 모델링·해결할 수 있는 상태.',
        prereq: ['TRIG_GRAPH_BASIC', 'TRIG_IDENT_BASIC', 'TRIG_ADD_FORMULAE', 'TRI_SOLVE_GENERAL'],
      },
    ],
  },
  {
    boss_id: 'TS_SEQ_PROOF',
    name_ko: '수열·수학적 귀납법',
    description_ko:
      '수열의 규칙과 합 공식을 바탕으로, 자연수에 대한 명제를 수학적 귀납법으로 증명하는 보스 스킬. 등차·등비수열, 합 공식, 나눗셈·부등식 명제를 단계적으로 다룬다.',
    skills: [
      {
        id: 'NAT_NUM_BASIC',
        name_ko: '자연수와 수의 계열',
        domain: '수와 연산',
        level: 1,
        description_ko: '자연수의 나열(1,2,3,…)과 크기 비교, ‘n번째’라는 표현의 의미를 이해한다.',
        prereq: [],
      },
      {
        id: 'PATTERN_SIMPLE',
        name_ko: '수 배열에서 규칙 찾기',
        domain: '변화와 관계',
        level: 2,
        description_ko: '간단한 수의 나열에서 규칙을 찾아 다음 수를 예측하고, 말이나 식으로 표현할 수 있다.',
        prereq: ['NAT_NUM_BASIC'],
      },
      {
        id: 'SEQ_NOTATION_BASIC',
        name_ko: '수열 표기와 a_n',
        domain: '수열',
        level: 3,
        description_ko: '수열 {a_n} 표기와 n번째 항 a_n의 의미를 이해하고, 간단한 규칙에서 a_1, a_2, a_3,…를 구할 수 있다.',
        prereq: ['PATTERN_SIMPLE'],
      },
      {
        id: 'SEQ_ARITH_BASIC',
        name_ko: '등차수열 기초(차 일정)',
        domain: '수열',
        level: 3,
        description_ko: '항 사이의 차이가 일정한 등차수열의 의미를 이해하고, 몇 개 항을 구할 수 있다.',
        prereq: ['SEQ_NOTATION_BASIC'],
      },
      {
        id: 'SEQ_GEOM_BASIC',
        name_ko: '등비수열 기초(비율 일정)',
        domain: '수열',
        level: 3,
        description_ko: '항 사이의 비율이 일정한 등비수열의 의미를 이해하고, 몇 개 항을 구할 수 있다.',
        prereq: ['SEQ_NOTATION_BASIC'],
      },
      {
        id: 'SEQ_GENERAL_FORM',
        name_ko: '등차·등비수열의 일반항',
        domain: '수열',
        level: 4,
        description_ko:
          '등차수열 a_n = a_1 + (n-1)d, 등비수열 a_n = a_1 r^{n-1} 의 일반항 공식을 이해하고, 주어진 조건에서 a_n을 구할 수 있다.',
        prereq: ['SEQ_ARITH_BASIC', 'SEQ_GEOM_BASIC'],
      },
      {
        id: 'CALC_SIGMA',
        name_ko: '시그마(Σ) 기호를 이용한 합 표현',
        domain: '수열/해석',
        level: 4,
        description_ko: '1+2+…+n, 등차·등비수열의 합 등을 Σ 기호로 간단히 표현하고, 기본적인 Σ 계산을 할 수 있다.',
        prereq: ['SEQ_GENERAL_FORM'],
      },
      {
        id: 'PROP_STATEMENT_BASIC',
        name_ko: '명제와 참·거짓',
        domain: '논리',
        level: 4,
        description_ko: '문장이 명제인지 아닌지 구분하고, 자연수 n에 대한 명제 P(n)의 개념을 이해한다.',
        prereq: ['NAT_NUM_BASIC'],
      },
      {
        id: 'LOGIC_IMPLICATION',
        name_ko: '논리적 함의와 ‘이면’ 구조',
        domain: '논리',
        level: 4,
        description_ko: "조건문 ‘P이면 Q이다’의 의미를 이해하고, P(n)→P(n+1) 형태의 조건을 말로 설명할 수 있다.",
        prereq: ['PROP_STATEMENT_BASIC'],
      },
      {
        id: 'INDUCTION_IDEA',
        name_ko: '수학적 귀납법 아이디어(계단 비유)',
        domain: '귀납법',
        level: 5,
        description_ko:
          'P(1)이 참이고, 임의의 자연수 k에 대해 P(k)가 참이면 P(k+1)도 참임을 보이면 모든 자연수에 대해 P(n)이 참이라는 아이디어를 직관적으로 이해한다.',
        prereq: ['LOGIC_IMPLICATION'],
      },
      {
        id: 'INDUCTION_BASE_STEP',
        name_ko: '기초 단계와 귀납 단계 쓰기',
        domain: '귀납법',
        level: 5,
        description_ko: "P(1)이 참임을 확인하는 ‘기초 단계’와 P(k)→P(k+1)를 보이는 ‘귀납 단계’를 명확히 구분하여 서술할 수 있다.",
        prereq: ['INDUCTION_IDEA'],
      },
      {
        id: 'INDUCTION_SUM_N',
        name_ko: '1+2+…+n = n(n+1)/2 증명',
        domain: '귀납법/수열',
        level: 6,
        description_ko: '수학적 귀납법을 사용하여 1부터 n까지의 합 공식 n(n+1)/2 를 증명할 수 있다.',
        prereq: ['INDUCTION_BASE_STEP', 'CALC_SIGMA'],
      },
      {
        id: 'INDUCTION_SUM_SQUARES',
        name_ko: '1²+2²+…+n² 공식 증명(심화)',
        domain: '귀납법/수열',
        level: 6,
        description_ko: '수학적 귀납법으로 1²+2²+…+n² 에 대한 공식을 유도·증명하는 과정을 따라갈 수 있다.',
        prereq: ['INDUCTION_BASE_STEP', 'CALC_SIGMA'],
      },
      {
        id: 'INDUCTION_SEQ_FORMULAE',
        name_ko: '등차·등비수열 공식의 귀납적 증명',
        domain: '귀납법/수열',
        level: 7,
        description_ko: '등차·등비수열의 일반항과 합 공식을 수학적 귀납법으로 증명할 수 있다.',
        prereq: ['SEQ_GENERAL_FORM', 'INDUCTION_BASE_STEP'],
      },
      {
        id: 'INDUCTION_DIVISIBILITY',
        name_ko: '나눗셈·배수 관련 명제의 귀납법 증명',
        domain: '귀납법/수론 기초',
        level: 7,
        description_ko: 'n³-n 이 항상 3의 배수임과 같은 나눗셈·배수 명제를 귀납법으로 증명할 수 있다.',
        prereq: ['INDUCTION_BASE_STEP'],
      },
      {
        id: 'INDUCTION_INEQUALITY',
        name_ko: '부등식 명제의 귀납법 증명(심화)',
        domain: '귀납법',
        level: 7,
        description_ko: '간단한 부등식 명제(예: 2^n ≥ n+1 등)를 수학적 귀납법으로 증명하는 구조를 이해한다.',
        prereq: ['INDUCTION_BASE_STEP', 'EXP_LAWS'],
      },
      {
        id: 'TS_SEQ_PROOF',
        name_ko: '보스: 수열·수학적 귀납법 마스터',
        domain: '보스',
        level: 8,
        description_ko:
          '수열의 일반항·합 공식, 시그마 표현, 명제·함의·귀납법 구조를 모두 연결하여 다양한 유형의 수열·나눗셈·부등식 명제를 스스로 설정하고 수학적 귀납법으로 증명할 수 있는 상태.',
        prereq: ['INDUCTION_SUM_N', 'INDUCTION_SEQ_FORMULAE', 'INDUCTION_DIVISIBILITY', 'INDUCTION_INEQUALITY'],
      },
    ],
  },
  {
    boss_id: 'TS_CONIC',
    name_ko: '이차곡선(포물선·타원·쌍곡선)',
    description_ko:
      '좌표평면, 직선과 원의 방정식, 이차함수와 완전제곱을 바탕으로 포물선·타원·쌍곡선의 표준형과 그래프, 매개변수의 의미, 직선과의 위치 관계까지 해석하는 보스 단원.',
    skills: [
      {
        id: 'NUM_INT_FRAC',
        name_ko: '정수·유리수의 사칙연산',
        domain: '수와 연산',
        level: 1,
        description_ko: '정수·분수·소수의 사칙연산과 간단한 식 계산을 정확히 할 수 있다.',
        prereq: [],
      },
      {
        id: 'ALG_EXPR_BASIC',
        name_ko: '문자식과 일차식',
        domain: '대수',
        level: 2,
        description_ko: '상황을 문자식으로 나타내고, 일차식의 사칙연산과 간단한 방정식 풀이를 할 수 있다.',
        prereq: ['NUM_INT_FRAC'],
      },
      {
        id: 'COORD_PLANE',
        name_ko: '좌표평면과 점의 좌표',
        domain: '기하',
        level: 2,
        description_ko: '좌표평면에서 점을 (x, y)로 나타내고, 사분면과 좌표의 의미를 이해한다.',
        prereq: ['NUM_INT_FRAC'],
      },
      {
        id: 'COORD_DIST_MID',
        name_ko: '두 점 사이 거리와 중점',
        domain: '기하',
        level: 3,
        description_ko: '두 점 사이 거리 공식과 선분의 중점 좌표를 이해하고 계산할 수 있다.',
        prereq: ['COORD_PLANE', 'NUM_INT_FRAC'],
      },
      {
        id: 'LINE_EQ_BASIC',
        name_ko: '직선의 방정식',
        domain: '기하',
        level: 3,
        description_ko: '기울기와 한 점을 이용해 직선의 방정식을 세우고, 두 직선의 평행·수직 관계를 설명할 수 있다.',
        prereq: ['COORD_PLANE', 'ALG_EXPR_BASIC'],
      },
      {
        id: 'CIRCLE_EQ_BASIC',
        name_ko: '원의 방정식',
        domain: '기하',
        level: 4,
        description_ko:
          '중심과 반지름이 주어진 원의 방정식 (x-a)^2 + (y-b)^2 = r^2 를 세울 수 있고, 일반형을 완전제곱으로 표준형으로 바꿀 수 있다.',
        prereq: ['COORD_DIST_MID', 'ALG_EXPR_BASIC'],
      },
      {
        id: 'FUNC_QUAD_BASIC',
        name_ko: '이차함수와 포물선 그래프',
        domain: '함수',
        level: 4,
        description_ko: '이차함수 y = ax^2 + bx + c 의 그래프를 그리고, 꼭짓점·축·대칭성의 의미를 이해한다.',
        prereq: ['ALG_EXPR_BASIC', 'NUM_INT_FRAC'],
      },
      {
        id: 'ALG_COMPLETE_SQUARE',
        name_ko: '완전제곱식 만들기(완전제곱완성)',
        domain: '대수',
        level: 4,
        description_ko: '이차식을 (x-p)^2 + q 꼴로 바꾸는 완전제곱 과정을 이해하고, 이차함수·이차곡선의 표준형을 얻는 데 활용할 수 있다.',
        prereq: ['FUNC_QUAD_BASIC'],
      },
      {
        id: 'CONIC_GENERAL_CLASSIFY',
        name_ko: '이차식으로부터 이차곡선 분류',
        domain: '기하',
        level: 5,
        description_ko: 'x, y에 대한 이차식을 완전제곱으로 정리하여 그것이 원·포물선·타원·쌍곡선 중 어느 것인지 분류할 수 있다.',
        prereq: ['CIRCLE_EQ_BASIC', 'ALG_COMPLETE_SQUARE'],
      },
      {
        id: 'CONIC_PARABOLA_BASIC',
        name_ko: '포물선의 정의와 표준형',
        domain: '기하',
        level: 5,
        description_ko:
          '한 점(초점)과 한 직선(준선)에서의 거리가 같은 점들의 자취로서 포물선을 이해하고, (x-h)^2 = 4p(y-k) 형태의 표준 방정식을 다룰 수 있다.',
        prereq: ['COORD_PLANE', 'ALG_COMPLETE_SQUARE', 'FUNC_QUAD_BASIC'],
      },
      {
        id: 'CONIC_ELLIPSE_BASIC',
        name_ko: '타원의 정의와 표준형',
        domain: '기하',
        level: 6,
        description_ko:
          '두 초점까지의 거리의 합이 일정한 점들의 자취로서 타원을 이해하고, (x-h)^2/a^2 + (y-k)^2/b^2 = 1 형태의 표준 방정식을 다룰 수 있다.',
        prereq: ['COORD_DIST_MID', 'CONIC_GENERAL_CLASSIFY'],
      },
      {
        id: 'CONIC_HYPERBOLA_BASIC',
        name_ko: '쌍곡선의 정의와 표준형',
        domain: '기하',
        level: 6,
        description_ko:
          '두 초점까지의 거리의 차가 일정한 점들의 자취로서 쌍곡선을 이해하고, (x-h)^2/a^2 - (y-k)^2/b^2 = 1 형태의 표준 방정식을 다룰 수 있다.',
        prereq: ['CONIC_GENERAL_CLASSIFY'],
      },
      {
        id: 'CONIC_PARAM_EFFECT',
        name_ko: '이차곡선에서 a, b, p 등의 의미',
        domain: '기하',
        level: 7,
        description_ko:
          '포물선, 타원, 쌍곡선의 표준형에서 파라미터 a, b, p, 중심 (h,k) 등이 그래프의 모양과 위치에 어떻게 영향을 주는지 설명할 수 있다.',
        prereq: ['CONIC_PARABOLA_BASIC', 'CONIC_ELLIPSE_BASIC', 'CONIC_HYPERBOLA_BASIC'],
      },
      {
        id: 'CONIC_LINE_INTERSECTION',
        name_ko: '직선과 이차곡선의 위치 관계',
        domain: '기하',
        level: 7,
        description_ko:
          '직선 방정식과 이차곡선 방정식을 연립하여 교점의 개수와 좌표를 구하고, 판별식을 이용해 서로의 위치 관계를 판단할 수 있다.',
        prereq: ['LINE_EQ_BASIC', 'CONIC_PARABOLA_BASIC', 'ALG_COMPLETE_SQUARE'],
      },
      {
        id: 'CONIC_TANGENT_BASIC',
        name_ko: '이차곡선의 접선 방정식(기초)',
        domain: '기하',
        level: 8,
        description_ko:
          '포물선이나 타원 위의 한 점에서의 접선 방정식을 기하적 성질 또는 미분의 직관으로 이해하고, 간단한 형태에서 구할 수 있다.',
        prereq: ['CONIC_PARABOLA_BASIC', 'CONIC_ELLIPSE_BASIC', 'ALG_EXPR_BASIC'],
      },
      {
        id: 'CONIC_REFLECTION_APP',
        name_ko: '포물선의 반사 성질·타원의 반사 성질',
        domain: '모델링',
        level: 8,
        description_ko:
          '포물선의 반사 성질(초점에서 나온 빛이 축과 평행하게 반사됨)과 타원의 반사 성질을 이해하고, 접시형 안테나·홀대 회의실 설계 등의 간단한 모델링 문제에 적용할 수 있다.',
        prereq: ['CONIC_PARABOLA_BASIC', 'CONIC_ELLIPSE_BASIC'],
      },
      {
        id: 'TS_CONIC',
        name_ko: '보스: 이차곡선 마스터',
        domain: '보스',
        level: 9,
        description_ko:
          '좌표평면·직선·원·이차함수에 기반해 포물선·타원·쌍곡선의 표준형과 그래프, 파라미터의 의미, 직선과의 위치 관계, 단순 접선·반사 성질까지 연결해 설명하고 문제를 풀 수 있는 상태.',
        prereq: [
          'LINE_EQ_BASIC',
          'CIRCLE_EQ_BASIC',
          'FUNC_QUAD_BASIC',
          'ALG_COMPLETE_SQUARE',
          'CONIC_PARABOLA_BASIC',
          'CONIC_ELLIPSE_BASIC',
          'CONIC_HYPERBOLA_BASIC',
          'CONIC_PARAM_EFFECT',
          'CONIC_LINE_INTERSECTION',
        ],
      },
    ],
  },
  {
    boss_id: 'TS_VECTOR_3D',
    name_ko: '벡터·공간좌표',
    description_ko:
      '평면벡터에서 시작해 공간좌표와 공간벡터, 내적을 이용한 거리·각·위치 관계, 공간 직선·평면의 방정식과 공간도형 해석까지 잇는 보스 단원.',
    skills: [
      {
        id: 'NUM_INT_FRAC',
        name_ko: '정수·유리수의 사칙연산',
        domain: '수와 연산',
        level: 1,
        description_ko: '좌표와 벡터 성분 계산을 위해 정수·분수·소수의 사칙연산을 정확히 할 수 있다.',
        prereq: [],
      },
      {
        id: 'COORD_PLANE',
        name_ko: '좌표평면과 점의 좌표',
        domain: '기하',
        level: 2,
        description_ko: '평면에서 점을 (x, y)로 나타내고, 두 점 사이 거리와 중점의 의미를 이해한다.',
        prereq: ['NUM_INT_FRAC'],
      },
      {
        id: 'VEC_PLANE_BASIC',
        name_ko: '평면벡터의 정의와 성분',
        domain: '벡터',
        level: 3,
        description_ko: '평면에서 화살표로 표현되는 벡터의 크기와 방향, 성분표현 (a, b)을 이해한다.',
        prereq: ['COORD_PLANE'],
      },
      {
        id: 'VEC_PLANE_ADD_SCALAR',
        name_ko: '벡터의 덧셈·뺄셈·실수배',
        domain: '벡터',
        level: 3,
        description_ko: '평행사변형법칙으로 벡터를 더하고 빼며, 실수배를 통해 벡터의 길이를 조절하는 연산을 할 수 있다.',
        prereq: ['VEC_PLANE_BASIC', 'NUM_INT_FRAC'],
      },
      {
        id: 'VEC_PLANE_DOT',
        name_ko: '평면벡터의 내적',
        domain: '벡터',
        level: 4,
        description_ko: '내적의 정의 v·w = |v||w|cosθ 와 성분 내적 v·w = a1b1 + a2b2 를 이해하고, 두 벡터의 수직 여부나 각을 판단할 수 있다.',
        prereq: ['VEC_PLANE_BASIC', 'NUM_INT_FRAC'],
      },
      {
        id: 'VEC_PLANE_GEOM',
        name_ko: '벡터를 이용한 평면도형 해석',
        domain: '기하',
        level: 5,
        description_ko: '삼각형·평행사변형에서 변을 벡터로 나타내고, 내적을 이용해 길이·각·직교성을 해석할 수 있다.',
        prereq: ['VEC_PLANE_ADD_SCALAR', 'VEC_PLANE_DOT'],
      },
      {
        id: 'COORD_3D_BASIC',
        name_ko: '공간좌표와 점의 위치',
        domain: '기하',
        level: 4,
        description_ko: '공간에서 점을 (x, y, z)로 나타내고, 좌표축과 좌표평면의 의미를 이해한다.',
        prereq: ['COORD_PLANE', 'NUM_INT_FRAC'],
      },
      {
        id: 'VEC_3D_BASIC',
        name_ko: '공간벡터의 정의와 성분',
        domain: '벡터',
        level: 5,
        description_ko: '공간에서 벡터를 (a, b, c)로 나타내고, 평행이동을 통해 벡터를 자유롭게 놓을 수 있음을 이해한다.',
        prereq: ['COORD_3D_BASIC', 'VEC_PLANE_BASIC'],
      },
      {
        id: 'VEC_3D_ADD_SCALAR',
        name_ko: '공간벡터의 덧셈·실수배',
        domain: '벡터',
        level: 5,
        description_ko: '공간벡터의 덧셈·뺄셈·실수배를 성분 연산으로 계산하고, 기하적으로 해석할 수 있다.',
        prereq: ['VEC_3D_BASIC', 'NUM_INT_FRAC'],
      },
      {
        id: 'VEC_3D_DOT',
        name_ko: '공간벡터의 내적',
        domain: '벡터',
        level: 6,
        description_ko: '평면벡터 내적을 확장하여 공간벡터의 내적을 정의하고, 벡터 크기와 두 벡터 사이 각, 수직 여부를 판단할 수 있다.',
        prereq: ['VEC_3D_BASIC', 'NUM_INT_FRAC', 'VEC_PLANE_DOT'],
      },
      {
        id: 'GEO_3D_LINE_EQ',
        name_ko: '공간 직선의 방정식(벡터식·매개변수식)',
        domain: '기하',
        level: 6,
        description_ko: '한 점과 방향벡터를 이용해 공간 직선의 벡터 방정식과 매개변수 방정식을 세울 수 있다.',
        prereq: ['VEC_3D_BASIC', 'ALG_EXPR_BASIC'],
      },
      {
        id: 'GEO_3D_PLANE_EQ',
        name_ko: '공간 평면의 방정식',
        domain: '기하',
        level: 6,
        description_ko: '법선벡터와 한 점을 이용해 평면의 방정식 ax + by + cz + d = 0 을 세우고, 평행·수직 관계를 해석할 수 있다.',
        prereq: ['VEC_3D_BASIC', 'VEC_3D_DOT', 'ALG_EXPR_BASIC'],
      },
      {
        id: 'GEO_3D_DISTANCE',
        name_ko: '공간에서의 거리(점-점, 점-직선, 점-평면)',
        domain: '기하',
        level: 7,
        description_ko: '두 점 사이 거리, 점에서 평면까지의 거리, 점에서 직선까지의 거리를 벡터와 내적을 이용해 구할 수 있다.',
        prereq: ['VEC_3D_DOT', 'GEO_3D_PLANE_EQ', 'NUM_INT_FRAC'],
      },
      {
        id: 'GEO_3D_ANGLE',
        name_ko: '직선·평면 사이의 각',
        domain: '기하',
        level: 7,
        description_ko: '두 직선, 직선과 평면, 두 평면 사이의 각을 방향벡터·법선벡터와 내적을 이용해 정의하고 계산할 수 있다.',
        prereq: ['VEC_3D_DOT', 'GEO_3D_LINE_EQ', 'GEO_3D_PLANE_EQ'],
      },
      {
        id: 'GEO_3D_SHAPES',
        name_ko: '공간도형과 벡터 해석',
        domain: '기하',
        level: 8,
        description_ko:
          '정다면체, 각기둥, 각뿔 등 공간도형의 모서리·대각선·높이 등을 벡터로 나타내고, 거리·각·넓이·부피를 구하는 문제를 해결할 수 있다.',
        prereq: ['GEO_3D_DISTANCE', 'GEO_3D_ANGLE', 'VEC_3D_ADD_SCALAR'],
      },
      {
        id: 'TS_VECTOR_3D',
        name_ko: '보스: 벡터·공간좌표 마스터',
        domain: '보스',
        level: 9,
        description_ko:
          '평면벡터에서 공간벡터까지 내적·직선·평면 방정식을 자유롭게 다루고, 공간도형의 거리·각·위치 관계 문제를 벡터 언어로 모델링해 해결할 수 있는 상태.',
        prereq: [
          'VEC_PLANE_GEOM',
          'VEC_3D_DOT',
          'GEO_3D_LINE_EQ',
          'GEO_3D_PLANE_EQ',
          'GEO_3D_DISTANCE',
          'GEO_3D_ANGLE',
          'GEO_3D_SHAPES',
        ],
      },
    ],
  },
  {
    boss_id: 'TS_COMB_PROB',
    name_ko: '경우의 수·확률',
    description_ko:
      '작은 표본공간 나열부터 합·곱의 법칙, 순열·조합, 그리고 기본 확률·조건부확률까지를 한 줄로 묶는 보스 스킬.',
    skills: [
      { id: 'NUM_PLACEVALUE', name_ko: '자리값·수의 분해/합성', domain: '', level: 1, description_ko: '', prereq: [] },
      {
        id: 'ADD_SUB_MULTI',
        name_ko: '여러 자리 수 덧셈·뺄셈',
        domain: '',
        level: 1,
        description_ko: '',
        prereq: ['NUM_PLACEVALUE'],
      },
      {
        id: 'MULT_DIV_BASIC',
        name_ko: '곱셈·나눗셈 기초(구구단)',
        domain: '',
        level: 1,
        description_ko: '',
        prereq: ['ADD_SUB_MULTI'],
      },
      {
        id: 'FRAC_BASIC',
        name_ko: '분수의 뜻과 등분할',
        domain: '',
        level: 1,
        description_ko: '',
        prereq: ['MULT_DIV_BASIC'],
      },
      {
        id: 'FRAC_DEC_REL',
        name_ko: '분수와 소수의 관계',
        domain: '',
        level: 1,
        description_ko: '',
        prereq: ['FRAC_BASIC'],
      },
      {
        id: 'FRAC_DEC_OP',
        name_ko: '분수·소수의 사칙연산',
        domain: '',
        level: 1,
        description_ko: '',
        prereq: ['FRAC_DEC_REL'],
      },
      {
        id: 'INT_RATIONAL_OP',
        name_ko: '정수·유리수의 사칙연산',
        domain: '',
        level: 1,
        description_ko: '',
        prereq: ['FRAC_DEC_OP'],
      },
      {
        id: 'SET_BASIC_EVENTS',
        name_ko: '사건과 표본공간(집합 언어)',
        domain: '',
        level: 1,
        description_ko: '',
        prereq: ['NUM_PLACEVALUE'],
      },
      {
        id: 'LIST_OUTCOMES_SMALL',
        name_ko: '작은 표본공간 나열하기',
        domain: '',
        level: 1,
        description_ko: '',
        prereq: ['SET_BASIC_EVENTS', 'NUM_PLACEVALUE'],
      },
      {
        id: 'TREE_TABLE_OUTCOMES',
        name_ko: '나무·표를 이용한 경우 나열',
        domain: '',
        level: 1,
        description_ko: '',
        prereq: ['LIST_OUTCOMES_SMALL'],
      },
      {
        id: 'COUNT_RULE_ADD',
        name_ko: '합의 법칙(겹치지 않는 사건)',
        domain: '',
        level: 2,
        description_ko: '',
        prereq: ['TREE_TABLE_OUTCOMES', 'INT_RATIONAL_OP'],
      },
      {
        id: 'COUNT_RULE_MULT',
        name_ko: '곱의 법칙(순차 선택)',
        domain: '',
        level: 2,
        description_ko: '',
        prereq: ['TREE_TABLE_OUTCOMES', 'INT_RATIONAL_OP'],
      },
      {
        id: 'FACTORIAL_NOTATION',
        name_ko: '계승 n!의 의미',
        domain: '',
        level: 2,
        description_ko: '',
        prereq: ['MULT_DIV_BASIC'],
      },
      {
        id: 'PERM_BASIC',
        name_ko: '순열 P(n, r)의 뜻과 계산',
        domain: '',
        level: 3,
        description_ko: '',
        prereq: ['FACTORIAL_NOTATION', 'COUNT_RULE_MULT'],
      },
      {
        id: 'COMB_BASIC',
        name_ko: '조합 C(n, r)의 뜻과 계산',
        domain: '',
        level: 3,
        description_ko: '',
        prereq: ['PERM_BASIC', 'INT_RATIONAL_OP'],
      },
      {
        id: 'COUNT_MIXED_APPLIED',
        name_ko: '합·곱·순열·조합을 섞은 경우의 수',
        domain: '',
        level: 4,
        description_ko: '',
        prereq: ['COUNT_RULE_ADD', 'COUNT_RULE_MULT', 'PERM_BASIC', 'COMB_BASIC'],
      },
      {
        id: 'PROB_BASIC_EQUALLYLIKELY',
        name_ko: '동일한 가능성에서의 확률 p = 유리수/전체',
        domain: '',
        level: 3,
        description_ko: '',
        prereq: ['LIST_OUTCOMES_SMALL', 'INT_RATIONAL_OP'],
      },
      {
        id: 'PROB_EVENT_OPERATIONS',
        name_ko: '여러 사건의 합·곱·여사건',
        domain: '',
        level: 3,
        description_ko: '',
        prereq: ['PROB_BASIC_EQUALLYLIKELY'],
      },
      {
        id: 'PROB_COND_BASIC',
        name_ko: '조건부확률 P(A|B) 기초',
        domain: '',
        level: 4,
        description_ko: '',
        prereq: ['PROB_EVENT_OPERATIONS', 'COUNT_MIXED_APPLIED'],
      },
      {
        id: 'PROB_BAYES_INTRO',
        name_ko: '간단한 베이즈 정리 예시',
        domain: '',
        level: 4,
        description_ko: '',
        prereq: ['PROB_COND_BASIC'],
      },
      {
        id: 'TS_COMB_PROB',
        name_ko: '보스 스킬: 경우의 수·확률 마스터',
        domain: '',
        level: 5,
        description_ko: '',
        prereq: ['COUNT_MIXED_APPLIED', 'PROB_EVENT_OPERATIONS', 'PROB_COND_BASIC'],
      },
    ],
  },
  {
    boss_id: 'TS_PROB_STAT',
    name_ko: '확률분포·통계적 추정',
    description_ko:
      '확률변수와 확률분포, 기댓값·분산, 이항분포와 정규분포, 표본·모수·신뢰구간을 연결해 ‘데이터로 세상을 추정하는’ 전체 구조를 다루는 보스 스킬.',
    skills: [
      { id: 'NUM_PLACEVALUE', name_ko: '자리값·수의 분해/합성', domain: '', level: 1, description_ko: '', prereq: [] },
      {
        id: 'ADD_SUB_MULTI',
        name_ko: '여러 자리 수 덧셈·뺄셈',
        domain: '',
        level: 1,
        description_ko: '',
        prereq: ['NUM_PLACEVALUE'],
      },
      {
        id: 'MULT_DIV_BASIC',
        name_ko: '곱셈·나눗셈 기초(구구단)',
        domain: '',
        level: 1,
        description_ko: '',
        prereq: ['ADD_SUB_MULTI'],
      },
      {
        id: 'FRAC_BASIC',
        name_ko: '분수의 뜻과 등분할',
        domain: '',
        level: 1,
        description_ko: '',
        prereq: ['MULT_DIV_BASIC'],
      },
      {
        id: 'FRAC_DEC_REL',
        name_ko: '분수와 소수의 관계',
        domain: '',
        level: 1,
        description_ko: '',
        prereq: ['FRAC_BASIC'],
      },
      {
        id: 'FRAC_DEC_OP',
        name_ko: '분수·소수의 사칙연산',
        domain: '',
        level: 1,
        description_ko: '',
        prereq: ['FRAC_DEC_REL'],
      },
      {
        id: 'INT_RATIONAL_OP',
        name_ko: '정수·유리수의 사칙연산',
        domain: '',
        level: 1,
        description_ko: '',
        prereq: ['FRAC_DEC_OP'],
      },
      {
        id: 'PROB_BASIC_EQUALLYLIKELY',
        name_ko: '기초 확률 p = 경우의 수 비',
        domain: '',
        level: 2,
        description_ko: '',
        prereq: ['INT_RATIONAL_OP'],
      },
      {
        id: 'PROB_EVENT_OPERATIONS',
        name_ko: '사건의 합·곱·여사건(복습)',
        domain: '',
        level: 2,
        description_ko: '',
        prereq: ['PROB_BASIC_EQUALLYLIKELY'],
      },
      {
        id: 'RANDVAR_DISCRETE_DEF',
        name_ko: '이산확률변수와 값/확률 쌍',
        domain: '',
        level: 3,
        description_ko: '',
        prereq: ['PROB_BASIC_EQUALLYLIKELY'],
      },
      {
        id: 'PMF_TABLE',
        name_ko: '확률분포표(값과 확률)',
        domain: '',
        level: 3,
        description_ko: '',
        prereq: ['RANDVAR_DISCRETE_DEF'],
      },
      {
        id: 'EXPECTATION_BASIC',
        name_ko: '기댓값 E[X] = Σ x·p(x)',
        domain: '',
        level: 4,
        description_ko: '',
        prereq: ['PMF_TABLE', 'INT_RATIONAL_OP'],
      },
      {
        id: 'VARIANCE_BASIC',
        name_ko: '분산·표준편차 Var[X]',
        domain: '',
        level: 4,
        description_ko: '',
        prereq: ['EXPECTATION_BASIC'],
      },
      {
        id: 'FACTORIAL_NOTATION',
        name_ko: '계승 n! 복습',
        domain: '',
        level: 2,
        description_ko: '',
        prereq: ['MULT_DIV_BASIC'],
      },
      {
        id: 'COMB_BASIC',
        name_ko: '조합 C(n, r) 복습',
        domain: '',
        level: 3,
        description_ko: '',
        prereq: ['FACTORIAL_NOTATION', 'INT_RATIONAL_OP'],
      },
      {
        id: 'BINOM_TRIALS',
        name_ko: '베르누이 시행과 이항실험',
        domain: '',
        level: 3,
        description_ko: '',
        prereq: ['PROB_BASIC_EQUALLYLIKELY'],
      },
      {
        id: 'BINOM_DIST_DEF',
        name_ko: '이항분포 X~B(n,p)의 정의',
        domain: '',
        level: 4,
        description_ko: '',
        prereq: ['BINOM_TRIALS', 'COMB_BASIC'],
      },
      {
        id: 'BINOM_MEAN_VAR',
        name_ko: '이항분포의 평균 np·분산 np(1-p)',
        domain: '',
        level: 4,
        description_ko: '',
        prereq: ['BINOM_DIST_DEF', 'EXPECTATION_BASIC'],
      },
      {
        id: 'NORMAL_DIST_INTRO',
        name_ko: '정규분포 모양과 매개변수(μ, σ)',
        domain: '',
        level: 5,
        description_ko: '',
        prereq: ['VARIANCE_BASIC'],
      },
      {
        id: 'STANDARDIZATION_Z',
        name_ko: '표준정규분포와 z-표',
        domain: '',
        level: 5,
        description_ko: '',
        prereq: ['NORMAL_DIST_INTRO', 'INT_RATIONAL_OP'],
      },
      {
        id: 'SAMPLE_MEAN_PROP',
        name_ko: '표본평균·표본비율과 분포 직관',
        domain: '',
        level: 6,
        description_ko: '',
        prereq: ['RANDVAR_DISCRETE_DEF', 'EXPECTATION_BASIC', 'VARIANCE_BASIC'],
      },
      {
        id: 'CI_MEAN_PROP',
        name_ko: '모평균·모비율의 신뢰구간',
        domain: '',
        level: 7,
        description_ko: '',
        prereq: ['SAMPLE_MEAN_PROP', 'STANDARDIZATION_Z'],
      },
      {
        id: 'STAT_ESTIMATION_REASON',
        name_ko: '추정 결과 해석과 의사결정',
        domain: '',
        level: 7,
        description_ko: '',
        prereq: ['CI_MEAN_PROP'],
      },
      {
        id: 'TS_PROB_STAT',
        name_ko: '보스 스킬: 확률분포·통계적 추정 마스터',
        domain: '',
        level: 8,
        description_ko: '',
        prereq: [
          'PMF_TABLE',
          'EXPECTATION_BASIC',
          'VARIANCE_BASIC',
          'BINOM_MEAN_VAR',
          'STAT_ESTIMATION_REASON',
          'TS_COMB_PROB',
        ],
      },
    ],
  },
];

export const SKILL_TREE_SEED_VERSION = 'math-bosses.v2';

export const STARTER_SKILL_TREE: SimpleSkillSpec[] = flattenBossSkills(BOSS_SKILL_GROUPS);

function flattenBossSkills(groups: BossSkillGroup[]): SimpleSkillSpec[] {
  const lookup = new Map<string, { name: string; prereq: Set<string> }>();

  groups.forEach((group) => {
    group.skills.forEach((skill) => {
      if (!lookup.has(skill.id)) {
        lookup.set(skill.id, { name: skill.name_ko, prereq: new Set<string>() });
      }
      const entry = lookup.get(skill.id)!;
      skill.prereq.forEach((req) => {
        if (typeof req === 'string' && req.trim().length > 0) {
          entry.prereq.add(req);
        }
      });
    });
  });

  return Array.from(lookup.entries())
    .map(([id, value]) => ({
      id,
      name: value.name,
      prereq: Array.from(value.prereq),
    }))
    .sort((a, b) => a.name.localeCompare(b.name, 'ko'));
}

export const BOSS_SKILLS = BOSS_SKILL_GROUPS;
