export const ROUTE_SEGMENTS = {
  login: 'login',
  signup: 'signup',
  dashboard: 'dashboard',
  graph: 'graph',
  map: 'map',
  tree: 'tree',
  report: 'report',
  preview: 'preview',
  learn: 'learn',
  eval: 'eval',
  health: 'health',
  mypage: 'mypage',
  homework: 'homework',
  author: 'author',
  authorImport: 'import',
  authorMiniFlow: 'mini',
  authorEditor: 'editor',
  authorResearchGraph: 'research-graph',
  authorValidate: 'validate',
  authorPublish: 'publish',
  authorHealth: 'health',
  authorHomework: 'homework'
} as const

export const ROUTES = {
  root: '/',
  login: `/${ROUTE_SEGMENTS.login}`,
  signup: `/${ROUTE_SEGMENTS.signup}`,
  dashboard: `/${ROUTE_SEGMENTS.dashboard}`,
  graph: `/${ROUTE_SEGMENTS.graph}`,
  map: `/${ROUTE_SEGMENTS.map}`,
  tree: `/${ROUTE_SEGMENTS.tree}`,
  report: `/${ROUTE_SEGMENTS.report}`,
  preview: `/${ROUTE_SEGMENTS.preview}`,
  learn: `/${ROUTE_SEGMENTS.learn}`,
  eval: `/${ROUTE_SEGMENTS.eval}`,
  health: `/${ROUTE_SEGMENTS.health}`,
  mypage: `/${ROUTE_SEGMENTS.mypage}`,
  homeworkSubmit: `/${ROUTE_SEGMENTS.mypage}/${ROUTE_SEGMENTS.homework}/:id`,
  author: `/${ROUTE_SEGMENTS.author}`,
  authorImport: `/${ROUTE_SEGMENTS.author}/${ROUTE_SEGMENTS.authorImport}`,
  authorMiniFlow: `/${ROUTE_SEGMENTS.author}/${ROUTE_SEGMENTS.authorMiniFlow}`,
  authorEditor: `/${ROUTE_SEGMENTS.author}/${ROUTE_SEGMENTS.authorEditor}`,
  authorResearchGraph: `/${ROUTE_SEGMENTS.author}/${ROUTE_SEGMENTS.authorResearchGraph}`,
  authorValidate: `/${ROUTE_SEGMENTS.author}/${ROUTE_SEGMENTS.authorValidate}`,
  authorPublish: `/${ROUTE_SEGMENTS.author}/${ROUTE_SEGMENTS.authorPublish}`,
  authorHealth: `/${ROUTE_SEGMENTS.author}/${ROUTE_SEGMENTS.authorHealth}`,
  authorHomework: `/${ROUTE_SEGMENTS.author}/${ROUTE_SEGMENTS.authorHomework}`
} as const
