name: ci-autofix
on:
  pull_request:
  workflow_dispatch:

jobs:
  test-and-autofix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -V
          pip install -U pip
          pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Run codex autofix loop
        env:
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_BASE_URL: ${{ secrets.LLM_BASE_URL }}
          LLM_MODEL: ${{ vars.LLM_MODEL }}
          CODEX_MAX_ITERS: 1
        run: |
          python tools/codex_loop.py || true
      - name: Create PR with autofixes (if any)
        uses: peter-evans/create-pull-request@v6
        with:
          title: "autofix: codex_loop suggestions"
          commit-message: "autofix: apply codex_loop patch"
          body: |
            This PR was generated by ci-autofix after running tools/codex_loop.py.
            Please review changes carefully. The loop attempts minimal, safe fixes.
          branch: "autofix/${{ github.run_id }}"

